### ISSUE TITLE
Hotsite "Vacinação Covid-19"

### ISSUE THREAD

**Issue by wforte88** [EscolaDeSaudePublica/coronavirus.ceara.gov.br#32]
## **Contexto**

O Governo do Estado do Ceará deu início à campanha de vacinação contra a Covid-19. A imunização ocorrerá em fases, de acordo com grupos prioritários. É necessário esclarecer o procedimento de vacinação para que trabalhadores da saúde e demais cidadãos estejam cientes da importância da vacina e em que fase poderão ser imunizados.

## **Tarefas**

- [x] #34 Página principal "Vacinação Covid-19"
- [x] #33 Fases da vacinação
- [x] #36 Vacinas disponíveis
- [x] #37Dúvidas frequentes
- [x] #39 Fato ou Fake
- [x] #38 Últimas notícias
- [x] #35 Plano de Operacionalização da Vacinação no Ceará

## Observações
[Pasta no Drive](https://drive.google.com/drive/u/0/folders/1GfphLZwW3tJpxu-KWjm_33l8wWFKl4MG)
